export const Dummyposts = [
    {id:1,
    description: "Good morning",
    photo: "../",
    likes: 0,
        },
    {id:2,
        description: "Beach",
        photo: "/path",
        likes: 5,
    },
    {id:3,
        description: "nightsky: Counting  stars",
        photo: "/path",
        likes: 2,
    },
    {id:4,
        description:"Movie time",
        photo: "/path",
        likes: 8,
    },
    {id:5,
        description: "Ready for dinner",
        photo: "/path",
        likes: 10,
    },
]