export const Dummyposts = [
    {id:1,
    description: "Good morning",
    photo: "./images/morning.jpg",
    likes: 0,
        },
    {id:2,
        description: "Beach",
        photo: "./images/beach.jpg",
        likes: 5,
    },
    {id:3,
        description: "nightsky: Counting  stars",
        photo: "./images/nightsky.jpg",
        likes: 2,
    },
    {id:4,
        description:"Movie time",
        photo: "./images/moviehall.jpg",
        likes: 8,
    },
    {id:5,
        description: "Ready for dinner",
        photo: "./images/diningtable.jpg",
        likes: 10,
    },
];